#!/usr/bin/env python3
"""Builds components/muse/avatar/muse_pixel.c from BonziBuddy's real sprite frames.

The frames (Mat's 8x8 sprite sheet sliced into 100x122 cells, see
Documents/BonziBuddy-sprites/README.md) are quantised to one shared 255-colour
palette; near-black pixels are the background (index 0: the face screen is
black). The generated C file implements muse_pixel.h: it picks a frame per
mode and animates blinks, idle breathing and the talking mouth, and scales the
frame to the canvas with nearest-neighbour sampling.

    python tools/muse/sprite_avatar.py [sprite-folder] [out.c]
"""
import os
import sys

from PIL import Image

SPRITES = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\mat_n\Documents\BonziBuddy-sprites"
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "..", "components", "muse", "avatar", "muse_pixel.c")

W, H = 100, 122
BG_MAX = 26   # a pixel this dark (all channels) is background

# name -> file, from the README's key-frame table
FRAMES = [
    ("idle_a", "f00.png"),
    ("idle_b", "f01.png"),
    ("blink", "f04.png"),
    ("listen", "f14.png"),
    ("think", "f36.png"),
    ("talk_o", "f02.png"),
    ("talk_c", "f03.png"),
    ("wave", "f20.png"),
    ("happy", "f21.png"),
    ("error", "f27.png"),
    ("sleep", "f16.png"),
]


def load(name):
    im = Image.open(os.path.join(SPRITES, name)).convert("RGB")
    if im.size != (W, H):
        im = im.crop((0, 0, W, H))
    px = im.load()
    # the slices bleed a sliver of the neighbouring cell at the edges: blank one pixel of border
    for x in range(W):
        px[x, 0] = px[x, H - 1] = (0, 0, 0)
    for y in range(H):
        px[0, y] = px[W - 1, y] = (0, 0, 0)
    return im


images = [load(f) for _, f in FRAMES]

# one palette for all frames: quantise them side by side, then split again
sheet = Image.new("RGB", (W * len(images), H))
for i, im in enumerate(images):
    sheet.paste(im, (i * W, 0))
quant = sheet.quantize(colors=255, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
pal = quant.getpalette()[: 255 * 3]
qpx = quant.load()
spx = sheet.load()


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


palette565 = [0] + [rgb565(pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2]) for i in range(255)]
frames = []
for i in range(len(images)):
    data = bytearray(W * H)
    for y in range(H):
        for x in range(W):
            r, g, b = spx[i * W + x, y]
            data[y * W + x] = 0 if max(r, g, b) < BG_MAX else qpx[i * W + x, y] + 1
    frames.append(bytes(data))


def c_bytes(b, per_line=32):
    lines = []
    for i in range(0, len(b), per_line):
        lines.append("    " + ", ".join("%d" % v for v in b[i:i + per_line]) + ",")
    return "\n".join(lines)


out = []
out.append("""// Copyright (c) Meta Platforms, Inc. and affiliates.

/*
 * AVATAR: BonziBuddy, from the real sprites.
 *
 * The genuine purple gorilla: BonziBuddy's own sprite frames (Mat's 8x8 sheet,
 * sliced to 100x122 cells), quantised to one 255-colour palette and shown with
 * nearest-neighbour scaling. He breathes between two idle frames, blinks now
 * and then, cups an ear to listen, scratches his chin to think, flaps his jaw
 * in time with the audio when he talks, waves on boot, beams when petted and
 * curls up to sleep. Generated by tools/muse/sprite_avatar.py: edit that, not this.
 */

#include "muse_pixel.h"

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#define SPR_W %d
#define SPR_H %d
#define MAP_MAX 512
#define BG565 0x0000   /* the face screen is black; index 0 is the keyed background */
""" % (W, H))

out.append("static const uint16_t PAL[256] = {\n" + c_bytes(palette565, 16).replace(",\n", ",\n") + "\n};\n")
for (name, _), data in zip(FRAMES, frames):
    out.append("static const uint8_t F_%s[SPR_W * SPR_H] = {\n%s\n};\n" % (name.upper(), c_bytes(data)))

out.append(r"""
/* ---- which frame, and where ------------------------------------------------- */

static const uint8_t *s_frame = F_IDLE_A;
static int s_bob;            /* vertical offset in sprite pixels (breathing) */
static int s_size = 192;
static int16_t s_xmap[MAP_MAX], s_ymap[MAP_MAX];   /* canvas x/y -> sprite x/y, -1 outside */
static float s_blink_until, s_next_blink = 3.0f;
static int s_talk_phase;
static float s_talk_t;

uint32_t muse_pixel_accent(muse_mode_t mode)
{
    switch (mode) {
    case MUSE_MODE_BOOT: return 0xa9c0ff;
    case MUSE_MODE_LISTENING: return 0x5cb8ff;
    case MUSE_MODE_THINKING: return 0xe07bff;
    case MUSE_MODE_SPEAKING: return 0x6ff0bf;
    case MUSE_MODE_ERROR: return 0xff5c5c;
    case MUSE_MODE_OFF: return 0x7c72d0;
    default: return 0xa77dff;
    }
}

void muse_pixel_render(const muse_pose_t *p)
{
    float t = p->t;
    /* Breathing: a slow one-pixel bob everywhere but asleep. */
    s_bob = p->mode == MUSE_MODE_OFF ? 0 : (int)lroundf(sinf(t * 2.0f) * 1.0f);
    if (p->happy > 0.3f) {
        s_frame = F_HAPPY;
        return;
    }
    switch (p->mode) {
    case MUSE_MODE_BOOT:
        s_frame = fmodf(t, 1.0f) < 0.5f ? F_WAVE : F_IDLE_A;
        return;
    case MUSE_MODE_LISTENING:
        s_frame = F_LISTEN;
        return;
    case MUSE_MODE_THINKING:
        s_frame = F_THINK;
        return;
    case MUSE_MODE_ERROR:
        s_frame = F_ERROR;
        return;
    case MUSE_MODE_OFF:
        s_frame = F_SLEEP;
        return;
    case MUSE_MODE_SPEAKING:
        /* The jaw follows the sound: open while there is level, flipping every ~110 ms so it chatters. */
        if (p->level > 0.06f) {
            if (t - s_talk_t > 0.11f) {
                s_talk_phase ^= 1;
                s_talk_t = t;
            }
            s_frame = s_talk_phase ? F_TALK_O : F_TALK_C;
        } else {
            s_frame = F_TALK_C;
        }
        return;
    default:
        break;
    }
    /* Idle: two frames swapped every two seconds, a blink every few seconds. */
    if (t >= s_next_blink) {
        s_blink_until = t + 0.14f;
        s_next_blink = t + 2.5f + fmodf(t * 7.31f, 3.5f);
    }
    if (t < s_blink_until) {
        s_frame = F_BLINK;
    } else {
        s_frame = fmodf(t, 4.0f) < 2.0f ? F_IDLE_A : F_IDLE_B;
    }
}

void muse_pixel_set_size(int px)
{
    s_size = px < MAP_MAX ? px : MAP_MAX;
    /* The sprite fills the canvas height; its width keeps the 100:122 shape, centred. */
    float k = (float)s_size / SPR_H;
    int w = (int)(SPR_W * k + 0.5f);
    int x0 = (s_size - w) / 2;
    for (int x = 0; x < s_size; x++) {
        int sx = (int)((x - x0) / k);
        s_xmap[x] = (int16_t)(x < x0 || sx < 0 || sx >= SPR_W ? -1 : sx);
    }
    for (int y = 0; y < s_size; y++) {
        int sy = (int)(y / k);
        s_ymap[y] = (int16_t)(sy < 0 || sy >= SPR_H ? -1 : sy);
    }
}

void muse_pixel_scale(uint16_t *dst, int stride_px, int x0, int x1, int y0, int y1)
{
    const uint8_t *frame = s_frame;
    int bob = s_bob;
    for (int y = y0; y <= y1; y++, dst += stride_px) {
        int yy = y - bob;
        int sy = yy >= 0 && yy < s_size ? s_ymap[yy] : -1;
        if (sy < 0) {
            for (int i = 0; i <= x1 - x0; i++) {
                dst[i] = BG565;
            }
            continue;
        }
        const uint8_t *row = frame + sy * SPR_W;
        for (int x = x0, i = 0; x <= x1; x++, i++) {
            int sx = x >= 0 && x < s_size ? s_xmap[x] : -1;
            dst[i] = sx < 0 ? BG565 : PAL[row[sx]];
        }
    }
}
""")

os.makedirs(os.path.dirname(os.path.abspath(OUT)), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out))
total = sum(len(fr) for fr in frames)
print("wrote %s: %d frames, %d bytes of sprite data, %d palette colours" % (OUT, len(frames), total, len(palette565)))
